# Generated by Django 5.2.5 on 2025-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travailleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('fonction', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Journalier', 'Journalier'), ('Temporaire', 'Temporaire')], default='CDI', max_length=20)),
                ('etat', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_debauche', models.DateField(blank=True, null=True)),
                ('motif_de_debauche', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['matricule', 'nom'],
            },
        ),
    ]
