# Generated by Django 5.2.5 on 2025-09-12 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travailleurs', '0002_alter_travailleurs_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(choices=[('permission', 'Permission'), ('repos', 'Repos'), ('conge', 'Congé'), ('sansmotif', 'SansMotif'), ('autre', 'Autre')], max_length=50)),
                ('type_absence', models.CharField(choices=[('heure', 'Heure'), ('jour', 'Jour')], max_length=10)),
                ('duree', models.FloatField(help_text='Durée en heures ou en jours selon le type')),
                ('travailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travailleurs.travailleurs')),
            ],
        ),
    ]
