# Generated by Django 5.2.6 on 2025-09-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travailleurs', '0003_absence'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('travailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travailleurs.travailleurs')),
            ],
            options={
                'unique_together': {('travailleur', 'date_debut', 'date_fin')},
            },
        ),
    ]
