# Generated by Django 5.2.6 on 2025-09-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travailleurs', '0004_nightshift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nightshift',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='nightshift',
            name='travailleur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travailleurs.travailleurs'),
        ),
    ]
