# Generated by Django 5.2.6 on 2025-09-14 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travailleurs', '0005_alter_nightshift_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
